version: "3.8"

services:
  database:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-volume:
    driver: local
